# JWT configurations
jwt.secret=local-development-secret-key-please-change-in-production
jwt.expirationMs=86400000
token.signing.key=uyrAxjO/5jsZTFepdsqfvzWDKauAA5lntCAuMm7IMEU=
jasypt.encryption.password=local-dev-encryption-key

# Frontend and backend URLs
spring.frontend.url=http://localhost:3000
spring.url=http://localhost:8080

# Token expiration configurations
token.accessToken.expiration=518400000
token.refreshToken.expiration=691200000

# File upload configurations
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Management endpoint configurations
management.endpoints.web.exposure.include=*
spring.main.lazy-initialization=true

# MongoDB connection URI
spring.data.mongodb.uri=mongodb://quash:quash123@mongodb:27017/quash?authSource=admin

# Cloud provider configuration
# For local development, we'll use a local file system
cloud.provider=gcp

# GCP-specific properties
gcp.bucket.name=quash
gcp.credentials.project-id=architech-t
gcp.credentials.client-email=quash-storage@architech-t.iam.gserviceaccount.com
gcp.credentials.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCl86OQ7xqzhV23\nVphLTOJD86JuwwNhph9b5WxAlZ0bA4iTDRN/W/Nv0ThQMsOla29k3i+h1FfQZAoe\nUdFLCUSu2AR19AF9hG3MAbixOMJQeVVocMu8q5dPKK0TM/A3/6+AET/oxDtd2/9R\nDLmokAoQ5jkErIH4QwmaOhiSfHJQgGA81ihDFF+J+2A1jiyblLXPbtf0+nvvVB5u\nfkMDBbo9GET1iqA7JKf3TBVOyMYjrpDu0Rzr8IFmSdjbS41ercAHruT12uoOJJkj\nJH/MVyzeyOs40axO11BStEsHudawsbxQC/se1EMH+yXMYDHxGpA3LP0ORNLpEM+A\nuhYnmziRAgMBAAECggEACcMD7V00nyLvy75/Mri+UOchOC47rJq6xVYAxj4hccrF\nVc8YWpl0VQYZL6suHoosETfPqfo6wyegqmlqLBA1bH/eUqOXPdn/Im0R1Jzv3eTR\nQmrrf85BK4x159yvhf/B7quKbJ0JwqA+YSG5lGyKpwqqh8zvpUSo6TFUgN4V/whX\nKHdC+wngtXtUqpgBhDHFPWKxcGTwjn8g4DVfJb0w2Rf8CJpelB/h+IK+VN1UbcEN\nIP2J+FnYC29+xCXxtylTU6aNTBSgZdZ5jUDyRY2o81J6CL3QAekK5+MV0wTQkLMo\nQHEphjlcve9ZY+Pw+NtL7CtM8QQrRALTFTX1QSHm5QKBgQDhVF7Fgub59KutEGHs\nKvMpgkGQAxQEqzt6ryPUmWrTfvgwJ/5d2Tbf8LWlXob+fcj/3sVEhGnO1TUw6zKO\nwuQXdY0pyAMUTtd0nwOjp+XLnifX84pG/7O22DfkajsTSrApWqtEKqlImjSYN001\nsfOu/dpdFa92kmeWwgXnHPKPbQKBgQC8ij3na7DbvsHKsOsDAb3vdQfF/QrXyoXG\nZ9HIgFOdS6iIAAoTQcY9zbU4p209V1yzcQgq/5jHJSE80kA3XKZQlEPKLZDhuvim\nB/MX8670VkbchtN6mXuLS18hJ0GCZx1fp0YOEbWbsqB5szNNCB9RkuOvxWvmMjWU\nq57aawJDNQKBgQDZXsDGHM+hVay/mUw9vfkxk9yXhsCq+Fy6r3YLQ6zQNm5KVmqG\nMmNDiTxSOWxU2Rcr7sWyoWJJC1jyxhHRsqTDFL2HDtIZpy0l7bhfCjseQIYDR4ef\nklDWFKNmkCxJIgXq/vK1IcqIpWoTZVXwdKi1qWIb5i2MXxPbVXTITR6ZyQKBgQCZ\nkmkWBYwLkfe8KBtlWZfiYoswZAre9qG8mHgyPwTcjPH7xTxvrxXQ5awFN6stWemy\naBFlJMjG/aFzLzcLYTY/UGVfW3o1w9whMTx7eAw8DcKugkvkAvy023HjSVx84Yz1\niwTvFNG+vuMj/il9R25rPaCkXcSjvqYSMTC1bJBtOQKBgQCItZzv1oICqrB958mk\nXe79nzt6CF1PEmqBvU9DXHRXk5SXoDKZ0PZZNcTVv9UGN6l0LcTBOehv3dzeYMGK\nlYTtpjTyv9TabBSzsPVJXX0GjHMaWK03f7idBc6usug50qEIHk2+jv8qPBJ9BGWh\nngMPrWG5pa4f1a69bp3fJnmw2A==\n-----END PRIVATE KEY-----

# AWS-specific properties
aws.access.key.id={AWS_ACCESS_KEY_ID}
aws.secret.access.key={AWS_SECRET_ACCESS_KEY}
aws.bucket.name={AWS_BUCKET_NAME}
aws.region={AWS_REGION}

# Azure-specific properties
azure.account.name={AZURE_ACCOUNT_NAME}
azure.account.key={AZURE_ACCOUNT_KEY}
azure.container.name={AZURE_CONTAINER_NAME}

# Mail Service configurations
spring.mail.host=smtp.gmail.com
spring.mail.username=liviogama@gmail.com
spring.mail.password=quem xzds pfkw szka
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
from.email.address=liviogama@gmail.com

# OAuth2 configurations for Google
spring.security.oauth2.client.registration.google.client-id={YOUR_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret={YOUR_CLIENT_SECRET}

# Atlassian Jira integration properties
spring.atlassian.jira.client_id={ATLASSIAN_JIRA_CLIENT_ID}
spring.atlassian.jira.client_secret={ATLASSIAN_JIRA_CLIENT_SECRET}
spring.atlassian.jira.auth_endpoint={ATLASSIAN_JIRA_AUTH_ENDPOINT}
spring.atlassian.jira.accessible_resource_endpoint={ATLASSIAN_JIRA_RESOURCE_ENDPOINT}

# Slack integration properties
spring.slack.heimdall_clientId={SLACK_HEIMDALL_CLIENT_ID}
spring.slack.heimdall_clientSecret={SLACK_HEIMDALL_CLIENT_SECRET}
spring.slack.redirectUri={SLACK_REDIRECT_URI}

# Linear integration properties
spring.linear.client_id={LINEAR_CLIENT_ID}
spring.linear.auth_endpoint={LINEAR_AUTH_ENDPOINT}
spring.linear.redirect_uri={LINEAR_REDIRECT_URI}
spring.linear.client_secret={LINEAR_CLIENT_SECRET}

# GitHub integration properties
spring.github.client_id={GITHUB_CLIENT_ID}
spring.github.client_secret={GITHUB_CLIENT_SECRET}
spring.github.redirect_url={GITHUB_REDIRECT_URL}
